# Generated by Django 5.1.1 on 2024-10-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0009_remove_game_homepageurl_remove_game_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default='not provided'),
        ),
    ]
