# Generated by Django 5.1.1 on 2024-10-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0015_alter_game_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_pictures/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pictures', to='Indie_Game.game')),
            ],
        ),
    ]
