# Generated by Django 5.1.1 on 2024-11-18 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unspecified', max_length=100)),
                ('publisher', models.CharField(default='unspecified', max_length=100)),
                ('genre', models.CharField(default='unspecified', max_length=200)),
                ('stage', models.CharField(default='unspecified', max_length=50)),
                ('cover_image', models.ImageField(default='default.jpg', upload_to='cover_images/')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(default='not provided')),
                ('short_intro', models.TextField(default='not provided')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('game_rating', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='Indie_Game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_comments', to='Indie_Game.discussion')),
            ],
            options={
                'db_table': 'Indie_Game_comment_temp',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Indie_Game.discussion')),
            ],
            options={
                'db_table': 'Indie_Game_comment',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='Indie_Game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_pictures/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_pictures', to='Indie_Game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_title', models.CharField(default='unspecified', max_length=100)),
                ('update_date', models.DateField()),
                ('patch_notes', models.TextField()),
                ('downloadable', models.URLField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Indie_Game.game')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Indie_Game.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='update_pictures/')),
                ('image_caption', models.TextField(default='not provided')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_pictures', to='Indie_Game.update')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('account_type', models.CharField(choices=[('dev', 'Developer'), ('player', 'Player')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepages', to='Indie_Game.userprofile'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='Indie_Game.userprofile'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Indie_Game.homepage')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Indie_Game.update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Indie_Game.userprofile')),
            ],
            options={
                'unique_together': {('user', 'update')},
            },
        ),
    ]
