# Generated by Django 5.1.1 on 2024-11-09 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('patch_notes', models.TextField()),
                ('downloadable', models.URLField(blank=True, max_length=500, null=True)),
                ('video', models.URLField(blank=True, max_length=500, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='Indie_Game.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='UpdatePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='update_pictures/')),
                ('image_caption', models.TextField(default='not provided')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_pictures', to='Indie_Game.update')),
            ],
        ),
    ]
