# Generated by Django 5.1.1 on 2024-11-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_title',
            field=models.CharField(max_length=100),
        ),
    ]
