# Generated by Django 5.1.1 on 2024-11-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0002_update_updatepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update_title',
            field=models.CharField(default='unspecified', max_length=100),
        ),
    ]
