# Generated by Django 5.1.1 on 2024-10-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0007_userprofile_avatar_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
