# Generated by Django 4.2.16 on 2024-10-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0018_alter_game_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='game_pictures/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='unspecified', max_length=50),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
