# Generated by Django 5.1.1 on 2024-09-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
