# Generated by Django 5.1.1 on 2024-10-02 18:58

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0004_remove_game_gameid_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
