# Generated by Django 5.1.1 on 2024-10-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0012_alter_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
