# Generated by Django 5.1.1 on 2024-10-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indie_Game', '0016_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pictures',
        ),
    ]
